import { PrismaClient } from '@prisma/client'
import { DEFAULT_WHITELIST } from '../lib/whitelist-defaults'

const prisma = new PrismaClient()

const receipts = [
  // ── THE MERIDIAN — SERIES 1 ────────────────────────────────────────────────
  {
    production_name: 'The Meridian — Series 1',
    date: new Date('2026-03-10'),
    department: 'VFX',
    crew_member_name: 'Sarah Chen',
    crew_role: 'VFX Supervisor',
    scene_usid: 'Scene_12B_VFX_Comp',
    script_date: '08 Mar 2026, Yellow Draft v4',
    ai_tool_used: 'Runway Gen-3',
    tool_status: 'GREEN',
    por_description: 'Generated background replacement footage for the desert sequence. Prompt: cinematic desert dusk, wide shot, golden hour, 35mm film grain.',
    sel_description: 'Selected take 3 of 5 — strongest colour temperature match to practical plates, most convincing horizon line.',
    adj_description: 'Colour graded to match practical footage, removed visible AI artefacts on horizon, added practical dust elements in post.',
    auth_signer: 'James Okafor',
    lct_required: false,
  },
  {
    production_name: 'The Meridian — Series 1',
    date: new Date('2026-03-12'),
    department: 'Writing',
    crew_member_name: 'Priya Nair',
    crew_role: 'Script Editor',
    scene_usid: 'Ep3_Act2_Draft',
    script_date: '10 Mar 2026, Yellow Draft v4',
    ai_tool_used: 'ChatGPT-4o',
    tool_status: 'AMBER',
    por_description: 'Generated alternate dialogue options for the confrontation scene in Act 2. Prompt: write three versions of a heated argument about inheritance, tone: naturalistic British drama.',
    sel_description: 'Selected version 2 — closest to characters established voices, retained the specific phrase about the will.',
    adj_description: 'Rewrote approximately 70% of selected output. Retained core dramatic structure only. All character voice adjustments made by writer.',
    auth_signer: 'Maya Lindqvist',
    lct_required: false,
    notes: 'Tool flagged YELLOW pending guild review',
  },
  {
    production_name: 'The Meridian — Series 1',
    date: new Date('2026-03-15'),
    department: 'Colour',
    crew_member_name: 'Tom Bauer',
    crew_role: 'Colourist',
    scene_usid: 'Ep1_Grade_Pass3',
    script_date: '10 Mar 2026, Yellow Draft v4',
    ai_tool_used: 'DaVinci Neural Engine',
    tool_status: 'GREEN',
    por_description: 'Used AI scene detection and auto-balance to generate initial grade pass for episode 1 day exteriors.',
    sel_description: 'Accepted AI-generated neutral balance as starting point for 12 of 34 shots in the sequence.',
    adj_description: 'Applied full manual grade over all shots. AI pass used as technical starting point only, not creative output.',
    auth_signer: 'James Okafor',
    lct_required: false,
  },
  {
    production_name: 'The Meridian — Series 1',
    date: new Date('2026-03-18'),
    department: 'Sound',
    crew_member_name: 'Amir Hassan',
    crew_role: 'Sound Designer',
    scene_usid: 'Ep2_Scene_7_Amb',
    script_date: '15 Mar 2026, Green Draft v1',
    ai_tool_used: 'Adobe Podcast AI',
    tool_status: 'GREEN',
    por_description: 'Generated ambient soundscape options for the night market sequence. Prompted with reference recordings and scene description.',
    sel_description: 'Selected layered ambient bed from output set 2 — best spatial depth, consistent with location sound.',
    adj_description: 'Layered with practical location recordings. Adjusted levels, added foley. Final mix bears substantial human intervention.',
    auth_signer: 'James Okafor',
    lct_required: false,
  },
  {
    production_name: 'The Meridian — Series 1',
    date: new Date('2026-03-20'),
    department: 'Art/Design',
    crew_member_name: 'Lucia Ferraro',
    crew_role: 'Production Designer',
    scene_usid: 'Set_Ref_Embassy_Int',
    script_date: '15 Mar 2026, Green Draft v1',
    ai_tool_used: 'Midjourney v6',
    tool_status: 'GREEN',
    por_description: 'Generated concept images for the embassy interior set. Prompt: 1970s brutalist embassy interior, dark wood panelling, low lighting, Cold War aesthetic.',
    sel_description: 'Selected two reference images from 24 generated — used as mood boards for set construction brief only, not reproduced directly.',
    adj_description: 'All set design drawn from scratch by human designer using AI images as reference only. Final set bears no direct visual reproduction of AI output.',
    auth_signer: 'Maya Lindqvist',
    lct_required: false,
  },
  {
    production_name: 'The Meridian — Series 1',
    date: new Date('2026-03-22'),
    department: 'VFX',
    crew_member_name: 'Sarah Chen',
    crew_role: 'VFX Supervisor',
    scene_usid: 'Ep4_CrowdSim_Stadium',
    script_date: '15 Mar 2026, Green Draft v1',
    ai_tool_used: 'Runway Gen-3',
    tool_status: 'GREEN',
    por_description: 'Generated crowd simulation reference for stadium sequence background. Prompted with camera angle and crowd density requirements.',
    sel_description: 'Used AI output as reference layer for manual crowd placement — selected movement patterns from generated footage.',
    adj_description: 'All final crowd elements hand-placed and animated by VFX team. AI reference used to inform scale and density only.',
    auth_signer: 'James Okafor',
    lct_required: true,
    lct_reference: 'LCT-MER-2026-004',
    notes: 'Background artists — union-cleared extras only. LCT token confirmed.',
  },

  // ── DARK WATER — FEATURE ───────────────────────────────────────────────────
  {
    production_name: 'Dark Water — Feature',
    date: new Date('2026-04-01'),
    department: 'Writing',
    crew_member_name: 'Eloise Vane',
    crew_role: 'Screenwriter',
    scene_usid: 'Scene_34_INT_CABIN',
    script_date: '30 Mar 2026, Blue Draft v2',
    ai_tool_used: 'ChatGPT-4o',
    tool_status: 'AMBER',
    por_description: 'Generated three alternate monologue options for Scene 34. Prompt: a grieving mother addresses her missing daughter through a letter, naturalistic, no melodrama.',
    sel_description: 'Selected version 2 — strongest emotional restraint, retained the line about the red coat.',
    adj_description: 'Rewrote 80% of selected output. Kept structural arc only. All voice and specific detail added by writer.',
    auth_signer: 'Fiona Garvey',
    lct_required: false,
  },
  {
    production_name: 'Dark Water — Feature',
    date: new Date('2026-04-03'),
    department: 'VFX',
    crew_member_name: 'Daniel Park',
    crew_role: 'VFX Artist',
    scene_usid: 'Scene_58_Ocean_Ext',
    script_date: '30 Mar 2026, Blue Draft v2',
    ai_tool_used: 'Runway Gen-3',
    tool_status: 'GREEN',
    por_description: 'Generated ocean storm reference footage for Scene 58. Multiple weather states generated from reference stills.',
    sel_description: 'Selected storm state 4 — wave height and spray density matched practical photography requirements.',
    adj_description: 'Integrated with practical plate photography. Extensive roto and compositing work by human VFX team.',
    auth_signer: 'Fiona Garvey',
    lct_required: false,
  },
  {
    production_name: 'Dark Water — Feature',
    date: new Date('2026-04-05'),
    department: 'Colour',
    crew_member_name: 'Ingrid Solberg',
    crew_role: 'DI Colourist',
    scene_usid: 'Reel_2_DI_Pass1',
    script_date: '30 Mar 2026, Blue Draft v2',
    ai_tool_used: 'DaVinci Neural Engine',
    tool_status: 'GREEN',
    por_description: 'AI-assisted shot matching across Reel 2 — 47 shots from three different camera packages normalised.',
    sel_description: 'Accepted AI match on 31 of 47 shots as a starting point. Rejected 16 as technically inaccurate.',
    adj_description: 'Full creative grade applied by colourist over all shots. AI match used for technical normalisation only.',
    auth_signer: 'Fiona Garvey',
    lct_required: false,
  },
  {
    production_name: 'Dark Water — Feature',
    date: new Date('2026-04-07'),
    department: 'Sound',
    crew_member_name: 'Kwame Mensah',
    crew_role: 'Re-recording Mixer',
    scene_usid: 'Reel_3_Mix_v2',
    script_date: '30 Mar 2026, Blue Draft v2',
    ai_tool_used: 'iZotope RX AI',
    tool_status: 'GREEN',
    por_description: 'AI dialogue restoration applied to location recordings from Reel 3 — wind noise and handling noise reduction.',
    sel_description: 'Applied AI restoration to 23 of 34 dialogue tracks where practical noise exceeded acceptable levels.',
    adj_description: 'All restoration decisions made by re-recording mixer. Manual passes applied after AI processing. No synthetic dialogue generated.',
    auth_signer: 'Fiona Garvey',
    lct_required: false,
  },
  {
    production_name: 'Dark Water — Feature',
    date: new Date('2026-04-08'),
    department: 'Art/Design',
    crew_member_name: 'Rosa Mendes',
    crew_role: 'Graphic Designer',
    scene_usid: 'Props_Newspaper_Hero',
    script_date: '30 Mar 2026, Blue Draft v2',
    ai_tool_used: 'Adobe Firefly',
    tool_status: 'GREEN',
    por_description: 'Generated layout options for hero prop newspaper front page. Prompted with 1980s tabloid design brief and fictional headline.',
    sel_description: 'Selected layout 3 of 6 — most authentic period typography and column structure.',
    adj_description: 'All text content written by props department. Layout substantially redesigned by graphic designer. AI used for initial column grid reference only.',
    auth_signer: 'Fiona Garvey',
    lct_required: false,
  },

  // ── SALT & IRON — DOCUMENTARY ──────────────────────────────────────────────
  {
    production_name: 'Salt & Iron — Documentary',
    date: new Date('2026-04-10'),
    department: 'Editorial',
    crew_member_name: 'Kwame Asante',
    crew_role: 'Editor',
    scene_usid: 'Seq_07_Montage_v3',
    script_date: '09 Apr 2026, Shooting Script',
    ai_tool_used: 'Adobe Premiere AI',
    tool_status: 'GREEN',
    por_description: 'Used AI scene detection and auto-reframe to generate rough assembly of the harbour sequence from 4 hours of rushes.',
    sel_description: 'Selected 11 of 34 AI-suggested cuts as starting points. Rejected all suggested music sync points.',
    adj_description: 'Fully re-cut the sequence by hand. AI assembly used only to identify usable takes. Final edit bears no structural resemblance to AI output.',
    auth_signer: 'Priya Mehta',
    lct_required: false,
  },
  {
    production_name: 'Salt & Iron — Documentary',
    date: new Date('2026-04-11'),
    department: 'Sound',
    crew_member_name: 'Lena Fischer',
    crew_role: 'Sound Editor',
    scene_usid: 'Seq_03_Interview_Clean',
    script_date: '09 Apr 2026, Shooting Script',
    ai_tool_used: 'Adobe Podcast AI',
    tool_status: 'GREEN',
    por_description: 'Applied AI noise reduction and voice enhancement to all interview recordings — 12 subjects, varying location quality.',
    sel_description: 'Applied enhancement to all 12 interview subjects. Reviewed each result before accepting.',
    adj_description: 'Manual EQ and level adjustment applied after AI processing. All editorial decisions made by sound editor.',
    auth_signer: 'Priya Mehta',
    lct_required: false,
  },
  {
    production_name: 'Salt & Iron — Documentary',
    date: new Date('2026-04-12'),
    department: 'Editorial',
    crew_member_name: 'Kwame Asante',
    crew_role: 'Editor',
    scene_usid: 'Seq_11_Archive_Match',
    script_date: '09 Apr 2026, Shooting Script',
    ai_tool_used: 'Adobe Premiere AI',
    tool_status: 'GREEN',
    por_description: 'Used AI to upscale and restore archival Super 8 footage from the 1970s for integration with contemporary material.',
    sel_description: 'Accepted AI upscale on 8 of 14 archival clips — rejected 6 where AI introduced visual artefacts inconsistent with period aesthetic.',
    adj_description: 'Grain structure added manually to all AI-upscaled clips to restore period feel. Colour graded by human colourist.',
    auth_signer: 'Priya Mehta',
    lct_required: false,
  },
  {
    production_name: 'Salt & Iron — Documentary',
    date: new Date('2026-04-14'),
    department: 'Writing',
    crew_member_name: 'Orla Byrne',
    crew_role: 'Documentary Writer',
    scene_usid: 'VO_Script_Ep2_Draft',
    script_date: '12 Apr 2026, Shooting Script Rev 1',
    ai_tool_used: 'ChatGPT-4o',
    tool_status: 'AMBER',
    por_description: 'Used AI to generate structural outline options for Episode 2 voiceover. Prompted with rough cut timecode and thematic notes.',
    sel_description: 'Selected structural arc from option 3 — chronological with thematic interruption at midpoint.',
    adj_description: 'All voiceover written from scratch by documentary writer using AI structural outline as a framework only. No AI-generated text used in final script.',
    auth_signer: 'Priya Mehta',
    lct_required: false,
    notes: 'ChatGPT flagged YELLOW — under review by production legal re: WGA consultation',
  },
  {
    production_name: 'Salt & Iron — Documentary',
    date: new Date('2026-04-15'),
    department: 'Art/Design',
    crew_member_name: 'Ben Okoro',
    crew_role: 'Motion Graphics Designer',
    scene_usid: 'Title_Card_Main_v4',
    script_date: '12 Apr 2026, Shooting Script Rev 1',
    ai_tool_used: 'Adobe Firefly',
    tool_status: 'GREEN',
    por_description: 'Generated texture and background options for main title card. Prompted with corroded iron and salt flat reference.',
    sel_description: 'Selected texture set 2 from 8 generated — most authentic industrial quality, consistent with documentary tone.',
    adj_description: 'All typography, layout and animation designed by motion graphics designer. AI textures used as background elements only, heavily treated.',
    auth_signer: 'Priya Mehta',
    lct_required: false,
  },
]

async function main() {
  console.log('Seeding database…')

  await prisma.receipt.deleteMany()

  for (const data of receipts) {
    const receipt = await prisma.receipt.create({ data })

    const { createHash } = await import('crypto')
    const hash = createHash('sha256')
      .update(JSON.stringify(receipt, Object.keys(receipt as object).sort()))
      .digest('hex')

    await prisma.receipt.update({
      where: { id: receipt.id },
      data: { twin_lock_hash: hash },
    })
  }

  console.log(`Seeded ${receipts.length} receipts across 3 productions.`)

  await prisma.whitelistEntry.deleteMany()
  await prisma.whitelistEntry.createMany({
    data: DEFAULT_WHITELIST.map((e) => ({
      toolName: e.toolName,
      displayName: e.displayName,
      status: e.status,
      condition: e.condition,
      requiresLCT: e.requiresLCT,
    })),
  })

  console.log(`Seeded ${DEFAULT_WHITELIST.length} whitelist entries.`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
