export interface WhitelistDefault {
  toolName: string
  displayName: string
  department: string
  status: 'GREEN' | 'AMBER' | 'RED'
  condition: string | null
  requiresLCT: boolean
}

export const DEFAULT_WHITELIST: WhitelistDefault[] = [

  // ── WRITING AND DEVELOPMENT ──────────────────────────────────────────────────
  {
    toolName: 'chatgpt plus / gpt-4o',
    displayName: 'ChatGPT Plus / GPT-4o',
    department: 'Writing',
    status: 'AMBER',
    condition: 'General research and brainstorming only. Do not submit script pages or confidential production material. Training data opt-out available but not default.',
    requiresLCT: false,
  },
  {
    toolName: 'claude (anthropic)',
    displayName: 'Claude (Anthropic)',
    department: 'Writing',
    status: 'AMBER',
    condition: 'Zero training data use on paid plans. Confirm plan type before use. Suitable for research, drafting, and development work.',
    requiresLCT: false,
  },
  {
    toolName: 'final draft companion',
    displayName: 'Final Draft Companion',
    department: 'Writing',
    status: 'GREEN',
    condition: 'Local processing. No cloud submission of script content. No training data use confirmed by Final Draft.',
    requiresLCT: false,
  },
  {
    toolName: 'writerduet ai features',
    displayName: 'WriterDuet AI features',
    department: 'Writing',
    status: 'AMBER',
    condition: 'Cloud-based. Confirm data processing agreement. Do not submit confidential production material without enterprise agreement.',
    requiresLCT: false,
  },
  {
    toolName: 'arc studio ai features',
    displayName: 'Arc Studio AI features',
    department: 'Writing',
    status: 'AMBER',
    condition: 'Cloud-based. Confirm data processing agreement before use.',
    requiresLCT: false,
  },
  {
    toolName: 'gemini for google docs',
    displayName: 'Gemini for Google Docs',
    department: 'Writing',
    status: 'AMBER',
    condition: 'Cloud Tenant Monitor required. GDPR data processing agreement required. Do not submit confidential material without enterprise agreement.',
    requiresLCT: false,
  },
  {
    toolName: 'microsoft copilot in word',
    displayName: 'Microsoft Copilot in Word',
    department: 'Writing',
    status: 'AMBER',
    condition: 'Cloud Tenant Monitor required. Enterprise data protection available. Confirm M365 plan before use.',
    requiresLCT: false,
  },

  // ── PRODUCTION AND SCHEDULING ────────────────────────────────────────────────
  {
    toolName: 'streamline ai',
    displayName: 'Streamline AI',
    department: 'Production',
    status: 'GREEN',
    condition: 'Production management tool. No creative content submission. Commercial indemnity provided.',
    requiresLCT: false,
  },
  {
    toolName: 'movie magic scheduling ai',
    displayName: 'Movie Magic Scheduling with AI features',
    department: 'Production',
    status: 'GREEN',
    condition: 'Local processing. Scheduling data only. No creative content submitted.',
    requiresLCT: false,
  },
  {
    toolName: 'sightlines',
    displayName: 'Sightlines',
    department: 'Locations',
    status: 'AMBER',
    condition: 'Cloud-based location analysis. No script or creative material to be submitted.',
    requiresLCT: false,
  },
  {
    toolName: 'cinapse',
    displayName: 'Cinapse',
    department: 'Production',
    status: 'AMBER',
    condition: 'Cloud-based. Confirm data processing agreement. Script material submitted so enterprise agreement required.',
    requiresLCT: false,
  },

  // ── CAMERA AND ON-SET ────────────────────────────────────────────────────────
  {
    toolName: 'davinci resolve neural engine (on-set)',
    displayName: 'DaVinci Resolve Neural Engine (On-Set)',
    department: 'Camera',
    status: 'GREEN',
    condition: 'Local processing. Blackmagic Design confirmed no training data use.',
    requiresLCT: false,
  },
  {
    toolName: 'assimilate scratch ai',
    displayName: 'Assimilate Scratch with AI features',
    department: 'Camera',
    status: 'GREEN',
    condition: 'Local processing. No cloud transmission.',
    requiresLCT: false,
  },
  {
    toolName: 'adobe frame.io ai',
    displayName: 'Adobe Frame.io with AI review features',
    department: 'Camera',
    status: 'AMBER',
    condition: 'Cloud-based. Confirm data processing agreement. Footage transmitted so GDPR compliance required.',
    requiresLCT: false,
  },
  {
    toolName: 'colorfront on-set dailies ai',
    displayName: 'Colorfront On-Set Dailies AI',
    department: 'Camera',
    status: 'GREEN',
    condition: 'Local processing. No training data use confirmed.',
    requiresLCT: false,
  },
  {
    toolName: 'sony catalyst browse ai',
    displayName: 'Sony Catalyst Browse with AI features',
    department: 'Camera',
    status: 'GREEN',
    condition: 'Local processing. Sony confirmed no training data use.',
    requiresLCT: false,
  },

  // ── ART DEPARTMENT AND CONCEPT ───────────────────────────────────────────────
  {
    toolName: 'adobe firefly',
    displayName: 'Adobe Firefly',
    department: 'Art Department',
    status: 'GREEN',
    condition: 'Trained on licensed Adobe Stock and public domain content only. Commercial indemnity provided.',
    requiresLCT: false,
  },
  {
    toolName: 'midjourney',
    displayName: 'Midjourney',
    department: 'Art Department',
    status: 'AMBER',
    condition: 'Training data position unclear for generated outputs. Commercial use licence available. No script or production-confidential material to be submitted. Reference and concept use only.',
    requiresLCT: false,
  },
  {
    toolName: 'dall-e 3 via chatgpt',
    displayName: 'DALL-E 3 via ChatGPT',
    department: 'Art Department',
    status: 'AMBER',
    condition: 'OpenAI training data opt-out not default. Concept and reference use only. Do not submit production-confidential material.',
    requiresLCT: false,
  },
  {
    toolName: 'runway gen-3 alpha',
    displayName: 'Runway Gen-3 Alpha',
    department: 'Art Department',
    status: 'AMBER',
    condition: 'Commercial licence with indemnity available on enterprise plan. Concept and reference use only at AMBER. GREEN upgrade available with enterprise agreement.',
    requiresLCT: false,
  },
  {
    toolName: 'stable diffusion (local)',
    displayName: 'Stable Diffusion (local)',
    department: 'Art Department',
    status: 'AMBER',
    condition: 'Open source, local deployment only. Copyright liability on training data unresolved but local deployment reduces risk. Concept use only.',
    requiresLCT: false,
  },
  {
    toolName: 'sketchup ai features',
    displayName: 'SketchUp AI features',
    department: 'Art Department',
    status: 'GREEN',
    condition: 'Local processing. Trimble confirmed no training data use.',
    requiresLCT: false,
  },
  {
    toolName: 'adobe substance ai',
    displayName: 'Adobe Substance AI',
    department: 'Art Department',
    status: 'GREEN',
    condition: 'Local processing. Adobe confirmed no training data use. Commercial indemnity provided.',
    requiresLCT: false,
  },

  // ── SOUND POST ───────────────────────────────────────────────────────────────
  {
    toolName: 'izotope rx 11',
    displayName: 'iZotope RX 11',
    department: 'Sound Post',
    status: 'GREEN',
    condition: 'Local processing. No cloud upload. No training data use.',
    requiresLCT: false,
  },
  {
    toolName: 'nuendo spectral layers',
    displayName: 'Nuendo Spectral Layers',
    department: 'Sound Post',
    status: 'GREEN',
    condition: 'Local processing. Steinberg confirmed no training data use.',
    requiresLCT: false,
  },
  {
    toolName: 'adobe podcast enhance speech',
    displayName: 'Adobe Podcast Enhance Speech',
    department: 'Sound Post',
    status: 'AMBER',
    condition: 'Cloud processing. Flag for GDPR if used on performer audio. Adobe confirmed no training data use. LCT required if performer voice submitted.',
    requiresLCT: true,
  },
  {
    toolName: 'auphonic',
    displayName: 'Auphonic',
    department: 'Sound Post',
    status: 'AMBER',
    condition: 'Cloud-based audio processing. Confirm data processing agreement. LCT required if performer voice submitted.',
    requiresLCT: true,
  },
  {
    toolName: 'descript',
    displayName: 'Descript',
    department: 'Sound Post',
    status: 'AMBER',
    condition: 'Cloud-based. LCT required if performer voice submitted. Do not use for voice cloning without explicit performer consent and legal sign-off.',
    requiresLCT: true,
  },
  {
    toolName: 'elevenlabs',
    displayName: 'ElevenLabs',
    department: 'Sound Post',
    status: 'RED',
    condition: 'Voice synthesis. LCT required before any performer voice processing. Performer consent must explicitly cover voice synthesis use. Commercial licence required. Legal review recommended before any use.',
    requiresLCT: true,
  },
  {
    toolName: 'suno ai (sound)',
    displayName: 'Suno AI',
    department: 'Sound Post',
    status: 'RED',
    condition: 'Music generation. Training data position contested. Copyright liability unresolved.',
    requiresLCT: false,
  },

  // ── EDITORIAL ────────────────────────────────────────────────────────────────
  {
    toolName: 'davinci resolve neural engine (editorial)',
    displayName: 'DaVinci Resolve Neural Engine (Editorial)',
    department: 'Editorial',
    status: 'GREEN',
    condition: 'Local processing. Blackmagic Design confirmed no training data use.',
    requiresLCT: false,
  },
  {
    toolName: 'adobe premiere pro scene edit detection',
    displayName: 'Adobe Premiere Pro — Scene Edit Detection & Text-Based Editing',
    department: 'Editorial',
    status: 'GREEN',
    condition: 'Local processing. Adobe confirmed no training data use for these features.',
    requiresLCT: false,
  },
  {
    toolName: 'adobe premiere pro generative extend',
    displayName: 'Adobe Premiere Pro — Generative Extend',
    department: 'Editorial',
    status: 'AMBER',
    condition: 'Generative AI feature. Confirm indemnity position for specific use before proceeding.',
    requiresLCT: false,
  },
  {
    toolName: 'avid media composer ai',
    displayName: 'Avid Media Composer AI features',
    department: 'Editorial',
    status: 'GREEN',
    condition: 'Local processing. Avid confirmed no training data use.',
    requiresLCT: false,
  },
  {
    toolName: 'topaz video ai',
    displayName: 'Topaz Video AI',
    department: 'Editorial',
    status: 'GREEN',
    condition: 'Local processing. No cloud upload.',
    requiresLCT: false,
  },
  {
    toolName: 'boris fx silhouette ai',
    displayName: 'Boris FX Silhouette AI',
    department: 'Editorial',
    status: 'GREEN',
    condition: 'Local processing. No training data use confirmed.',
    requiresLCT: false,
  },
  {
    toolName: 'after effects ai features',
    displayName: 'After Effects AI features',
    department: 'Editorial',
    status: 'GREEN',
    condition: 'Local processing (Roto Brush, Content-Aware Fill). Adobe confirmed no training data use.',
    requiresLCT: false,
  },

  // ── COLOUR / DI ──────────────────────────────────────────────────────────────
  {
    toolName: 'davinci resolve neural engine (colour / di)',
    displayName: 'DaVinci Resolve Neural Engine (Colour / DI)',
    department: 'Colour / DI',
    status: 'GREEN',
    condition: 'Local processing. Blackmagic Design confirmed no training data use.',
    requiresLCT: false,
  },
  {
    toolName: 'baselight ai features',
    displayName: 'Baselight with AI features',
    department: 'Colour / DI',
    status: 'GREEN',
    condition: 'Local processing. FilmLight confirmed no training data use.',
    requiresLCT: false,
  },
  {
    toolName: 'neat video',
    displayName: 'Neat Video',
    department: 'Colour / DI',
    status: 'GREEN',
    condition: 'Local noise reduction plugin. No data transmission.',
    requiresLCT: false,
  },
  {
    toolName: 'filmlight texture equaliser',
    displayName: 'FilmLight Texture Equaliser',
    department: 'Colour / DI',
    status: 'GREEN',
    condition: 'Local processing. No training data use.',
    requiresLCT: false,
  },

  // ── DELIVERY / QC ────────────────────────────────────────────────────────────
  {
    toolName: 'telestream vantage ai qc',
    displayName: 'Telestream Vantage with AI QC',
    department: 'Delivery / QC',
    status: 'GREEN',
    condition: 'Local or on-premises processing. No training data use confirmed.',
    requiresLCT: false,
  },
  {
    toolName: 'interra baton ai qc',
    displayName: 'Interra Baton AI QC',
    department: 'Delivery / QC',
    status: 'GREEN',
    condition: 'Local or on-premises processing. No training data use confirmed.',
    requiresLCT: false,
  },
  {
    toolName: 'ooona ai subtitling',
    displayName: 'Ooona AI subtitling',
    department: 'Delivery / QC',
    status: 'AMBER',
    condition: 'Cloud-based. Confirm data processing agreement. No performer voice data to be submitted without LCT.',
    requiresLCT: true,
  },
  {
    toolName: 'verbit ai transcription',
    displayName: 'Verbit AI transcription and subtitling',
    department: 'Delivery / QC',
    status: 'AMBER',
    condition: 'Cloud-based. GDPR data processing agreement required. LCT required if performer audio submitted.',
    requiresLCT: true,
  },

  // ── MUSIC AND SCORE ──────────────────────────────────────────────────────────
  {
    toolName: 'spitfire audio labs',
    displayName: 'Spitfire Audio LABS',
    department: 'Music',
    status: 'GREEN',
    condition: 'Local processing. No training data use.',
    requiresLCT: false,
  },
  {
    toolName: 'output ai features',
    displayName: 'Output AI features',
    department: 'Music',
    status: 'GREEN',
    condition: 'Local processing. No training data use confirmed.',
    requiresLCT: false,
  },
  {
    toolName: 'moises ai',
    displayName: 'Moises AI',
    department: 'Music',
    status: 'AMBER',
    condition: 'Cloud-based. Confirm licensing position for commercial use. No copyrighted third-party material to be submitted.',
    requiresLCT: false,
  },
  {
    toolName: 'suno ai (music)',
    displayName: 'Suno AI (Music)',
    department: 'Music',
    status: 'RED',
    condition: 'Music generation. Training data position contested. Copyright liability unresolved. Do not use on any production without legal sign-off.',
    requiresLCT: false,
  },
  {
    toolName: 'udio',
    displayName: 'Udio',
    department: 'Music',
    status: 'RED',
    condition: 'Music generation. Training data position contested. Copyright litigation ongoing. Do not use.',
    requiresLCT: false,
  },

  // ── VFX ─────────────────────────────────────────────────────────────────────
  {
    toolName: 'marz',
    displayName: 'MARZ',
    department: 'VFX',
    status: 'GREEN',
    condition: null,
    requiresLCT: false,
  },
  {
    toolName: 'flawless ai truesync',
    displayName: 'Flawless AI TrueSync',
    department: 'VFX',
    status: 'GREEN',
    condition: null,
    requiresLCT: false,
  },
  {
    toolName: 'metaphysic',
    displayName: 'Metaphysic',
    department: 'VFX',
    status: 'AMBER',
    condition: 'LCT required. Digital replica consent must be verified before use.',
    requiresLCT: true,
  },

  // ── SOUND (on-set / production sound) ────────────────────────────────────────
  {
    toolName: 'respeecher',
    displayName: 'Respeecher',
    department: 'Sound',
    status: 'AMBER',
    condition: 'LCT required. Voice synthesis consent must be verified before use.',
    requiresLCT: true,
  },
]
